### PR TITLE
Fix hands do not disappear

### LINKED ISSUE #1: Bug: Hands do not disappear when webcam image shows no hands
Right now, hands that are drawn on the screen do not disappear when hands disappear from the webcam image.

While originally by design, this needs to be fixed in a more elegant way. Ideally, we want to cached hand landmarks for 2-3 frames so that we can run pose recognition on the hands, but we want the hands to disappear after those frames elapse if the hands are still not in the webcam image.

### PR DESCRIPTION
**Pull request by tyrrr110**
fix #1

### CODE REVIEW

File: src/components/Story.js [hunk 1]
```diff
@@ -17,7 +18,7 @@ const Story = () => {
   // HACK: I should figure out a way to use xstate to migrate from loading to ready
   //  but b/c the async/await nature of the callbacks with Holistic, I'm leaving this hack in for now.
   const [loading, setLoading] = useState(true);
-  const [poseData, setPoseData] = useSetState({});
+  const [poseData, setPoseData] = useState({}); // doesn't momeize
```
Comment (afogel) [inline src/components/Story.js:21]: memoize :)

Comment (afogel) [reply src/components/Story.js:21]: also, if we're not using the `useSetState` hook, we should remove its import statement, too, right?
